#!/bin/bash

#=======================================================================
# HEADER
#=======================================================================
#% NAME
#%      Script Name - A brief description of your script.
#%
#=======================================================================
#% SYNOPSIS
#+      ${scriptName} [OPTION]... [ARGUMENT]...
#+
#=======================================================================
#% DESCRIPTION
#+      A detailed description of your script goes here.
#+      You can use multiple lines to provide more information.
#+
#=======================================================================
#+ OPTIONS
#+      -h, --help          Display this help message and exit
#%
#+      -v, --version       Display version information and exit
#%
#+      -l, --log-file      Custom log file location
#%                          Regex: ^[a-zA-Z0-9_/\.-]+$
#%
#+      -o, --option        Do nothing
#+
#=======================================================================
#+ EXAMPLES
#%      Example usages of ${scriptName}.
#+
#+      $ ${scriptName} -l script.log -o
#%          This example shows how to use the script with the log file
#%          set to "script.log", and -o option, that does nothing.
#+
#=======================================================================
#/ IMPLEMENTATION
#-      Version     ${scriptName} 1.0
#/      Author      Gabriel Nascimento
#/      Copyright   Copyright (c) Gabriel Nascimento (gnsilva.com)
#/      License     MIT License
#/
#=======================================================================
#) COPYRIGHT
#)      Copyright (c) 2023 Gabriel Nascimento:
#)      <https://opensource.org/licenses/MIT>.
#)
#)      Permission is hereby granted, free of charge, to any person
#)      obtaining a copy of this software and associated documentation
#)      files (the "Software"), to deal in the Software without
#)      restriction, including without limitation the rights to use,
#)      copy, modify, merge, publish, distribute, sublicense, and/or
#)      sell copies of the Software, and to permit persons to whom the
#)      Software is furnished to do so, subject to the following
#)      conditions:
#)
#)      The above copyright notice and this permission notice shall be
#)      included in all copies or substantial portions of the Software.
#)
#)      THE SOFTWARE IS PROVIDED "AS IS," WITHOUT WARRANTY OF ANY KIND,
#)      EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
#)      OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#)      NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#)      HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
#)      WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#)      FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
#)      OTHER DEALINGS IN THE SOFTWARE.
#)
#=======================================================================
# UTILS
#       Script "utils/_checkDependencies.sh"
#           Check if a given package exists
#
#       Script "utils/_create.sh"
#           Creates a file or a folder, if it does not exist
#
#       Script "utils/_doCountdown.sh"
#           Perform a countdown for the specified number of seconds
#
#       Script "utils/_displayHelp.sh"
#           Handles the help messages, either full or usage,
#           from the info on this header
#
#       Script "utils/_validateArguments.sh"
#           Used to validate a string or argument
#
#       Script "utils/_hasWritePermission.sh"
#           Check if user has write permission on a given folder
#
#       Trap "DEBUG"
#           This script uses a DEBUG trap when "_initLogger" is called,
#           which prints the output of all commands to a log file, and
#           by default it also does not print stderr and stdout
#           on the terminal, unless explicitly told to
#
#           To print command output on the terminal, redirect the output
#           to FD3 (eg: command >&3). Some commands like package
#           managers output to both stdout and stderr and may ask for
#           user input. In this case, redirect both FD1 and FD2 to FD3,
#           otherwise the user will not be aware of the command asking
#           for input (eg: command >&3 2>&3)
#
#           If you need to display a text on the terminal,
#           you can use the function "println", which redirects printf
#           to FD3, thus making it easier to type and distinguish which
#           text get shown to the user (eg: "println [MESSAGE]...")
#
#           You can use the function "log [MESSAGE]..." to ouput a
#           formated log message, prefixed with "+++" and the line
#           number to the log file. Otherwise, use echo or printf
#           command without a FD set
#
#           When presenting a user or a system with a specific message,
#           question, or request in order to elicit a response or input,
#           make sure to also redirect the message to FD3, otherwise it
#           will not output to the user
#           (eg: 'read -r -p "Input: " ans >&3')
#
#           If you need to request input from the user, you can use the
#           function "prompt", which redirects printf to FD3, thus
#           making it easier to redirect multiple prompts
#           (eg 'read -r -p "$(prompt "Input: ")" ans')
#
#=======================================================================
# DEBUG OPTIONS
    set +o xtrace
#       Trace the execution of the script (DEBUG)

    set +o noexec
#       Don't execute commands (Ignored by interactive shells)
#
#=======================================================================
# BASH OPTIONS
    set -o nounset  # Exposes unset variables
    set -o errexit  # Exit upon error, avoiding cascading errors
    set -o pipefail  # Unveils hidden failures
    set -o noclobber  # Avoid overwriting files (eg: echo "hi" > foo)
    set -o errtrace  # Inherit trap on ERR to functions and commands
    shopt -s nullglob  # Non-matching globs are removed ('*.foo' => '')
    shopt -s failglob  # Non-matching globs throw errors
    shopt -u nocaseglob  # Case insensitive globs
    shopt -s dotglob  # Wildcards match hidden files
    shopt -s globstar  # Recursive matches ('a/**/*.e' => 'a/b/c/d.e')
#
#=======================================================================
# TRAPS
    function _setTraps() {

        trap '{ set +o xtrace; } 2>/dev/null                     \
            ; PS4="+ [$(date +"%d/%m/%Y %H:%M:%S")] ${LINENO}: " \
            ; set -o xtrace' DEBUG

        trap "" SIGTSTP
        trap _exitTrap EXIT
        trap _ctrlC INT
        trap _errTrapper ERR
    }

    function _ctrlC() {
        trap "" INT  # Disable trap on CTRL_C to prevent recursion

        println "\nInterrupt signal intercepted! Exiting now..."
        exit 130
    }

    function _errTrapper() {

        local exitCode="${?}"

        trap "" ERR  # Disable trap on ERR to prevent recursion

        println "${scriptName}: An exception occurred during execution"
        println "Check the log file \"${scriptLogFile}\" for details."

        exit "${exitCode:-1}"
    }

    function _exitTrap() {

        local exitCode="${?}"

        trap "" EXIT  # Disable trap on EXIT to prevent recursion

        rm --recursive --force  \
            "${scriptTempDir}"  \
            "${scriptTempFile}"

        cd "${currentDir}"

        log "Script Terminated with exit status: ${exitCode:-1}"
        exit "${exitCode:-1}"
    }
#
#=======================================================================
#: END_OF_HEADER
#=======================================================================

# Section: Script Initialization

# shellcheck disable=1090
function _initVariables() {

    IFS=$' \t\n'

    currentDir="${PWD}"

    scriptParams=( "${@}" )
    scriptName="$(basename "${0}")"
    scriptDir="$(cd "$(dirname "${0}")" && pwd )"
    scriptPath="${scriptDir:?}/${scriptName:?}"
    scriptHead=$(grep --no-messages --line-number "^#: END" "${0}" \
        | head -1 \
        | cut --fields=1 --delimiter=:
    )

    scriptTempDir=$(mktemp --directory -t tmp.XXXXXXXXXX)
    scriptTempFile=$(mktemp -t tmp.XXXXXXXXXX)

    scriptLogFile="${scriptDir}"/logs/script.log
    mkdir --parents "$(dirname "${scriptLogFile}")" \
        || { local exitCode="${?}"
             printf "\nFailed to create log file on default directory: " >&2
             printf "\"%s\"" "${scriptLogFile}" >&2
             printf "\nMake sure it is a valid path and " >&2
             printf "that you have write permission.\n" >&2
             exit "${exitCode}"
           }

    msgInvalid="${scriptName}: invalid option"
    msgTryHelp="Try '${scriptName} --help' for more information."
}

# shellcheck disable=1090
function _initUtils() {
    local script
    for script in "${scriptDir}"/utils/_*.sh; do
        source "${script}"
    done
}

function _initLogger() {
    local filePath
    local filename
    local directory
    local parentDir
    local dir
    local argUsed=false
    local valuesToRemove=()
    local filteredParams=()

    while [[ "${#}" -gt 0 ]]; do
        case "${1:-}" in
            -l | --log-file )
                if [[ "${argUsed}" == true ]]; then
                    printf "%s: too much arguments\n" "${scriptName}" >&2
                    printf "%s\n" "${msgTryHelp}" >&2
                    exit 1
                fi
                shift

                filePath="${1:-}"
                if [[ -z "${filePath}" ]]; then
                    printf "%s: missing file operand\n" "${scriptName}" >&2
                    printf "%s\n" "${msgTryHelp}" >&2
                    exit 1
                fi

                directory=$(dirname "${filePath}" 2>/dev/null)
                if [[ ! "${directory}" =~ ^/ ]]; then
                    directory="${PWD?}/${directory}"
                fi

                filename=$(basename "${filePath}")
                if [[ ! "${directory}" =~ ^[a-zA-Z0-9_/\.-]+$          \
                    || ! "${filename}" =~ ^[a-zA-Z0-9_/\.-]+$ ]]; then

                    printf "%s: Invalid file or directory name\n" \
                        "${scriptName}" >&2
                    printf "%s\n" "${msgTryHelp}" >&2
                    exit 1
                fi

                dir="${directory}"
                while true; do
                    if [[ -w "${dir}" ]]; then
                        break
                    fi

                    parentDir=$(dirname "${dir}")
                    if [[ "${parentDir}" == "${dir}" ]]; then
                        printf "%s: " "${scriptName}" >&2
                        printf "cannot set log directory to " >&2
                        printf "\"%s\"" "${directory}" >&2
                        printf ": Permission Denied\n" >&2
                        exit 1
                    fi

                    dir="${parentDir}"
                done

                mkdir "${directory}" --parents            \
                    && touch "${directory:?}/${filename}" \

                scriptLogFile="${filePath}"
                argUsed=true

                valuesToRemove=( "-l" "--log-file" "${filePath}" )
                for element in "${scriptParams[@]}"; do
                    # Check if the element is in the list of values to remove
                    if [[ ! "${valuesToRemove[*]}" == *"${element}"* ]]; then
                        filteredParams+=("$element")
                    fi
                done
                scriptParams=( "${filteredParams[@]}" )
                ;;
            * )
                :
                ;;
        esac
        shift
    done

    cp /dev/null "${scriptLogFile}"
    exec 3>&1 1>>"${scriptLogFile}" 2>&1
}

function _traceVariables() {

    log "Origin cwd: ${currentDir}"
    log "Script parameter: ${scriptParams[*]}"
    log "Script name: ${scriptName}"
    log "Script directory: ${scriptDir}"
    log "Script path: ${scriptPath}"
    log "Script head size: ${scriptHead}"
    log "Script temp directory: ${scriptTempDir}"
    log "Script temp file: ${scriptTempFile}"
    log "Script log file: ${scriptLogFile}"
    log "Message invalid: ${msgInvalid}"
    log "Message try help: ${msgTryHelp}"
}

# Section: Script Helper Functions

function log() {

    command printf "+++ (%s): %b\n" "${BASH_LINENO[0]}" "${*}"
}

function println() {

    command printf "%b\n" "${*}" >&3
}

function prompt() {
    command printf "%s" "${*}" >&3
}

# Section: Script Functions

#TODO Define script functions here
# ...

# Section: Main Program

# shellcheck disable=SC1091
function _main() {

    if [[ "${#}" -lt 1 ]]; then
        displayHelpUsage >&3
        exit 0
    fi

    local i
    for i in "${@}"; do
        case "${i}" in
            -h | --help | help )
                displayFullHelp >&3
                exit 0
                ;;
            -v | --version | version )
                displayVersion >&3
                exit 0
                ;;
        esac
    done

    #TODO Define options logic here
    # ...

    cd "${scriptDir}" || exit 1
    while [[ "${#}" -gt 0 ]]; do
        case "${1:-}" in
            -o | --option )
                :
                ;;
            * )
                println "${msgInvalid} \"${1:-}\""
                println "${msgTryHelp}"
                exit 1
                ;;
        esac
        shift
    done

    #TODO Define script logic from here
    # ...
}

# Invoke main with args only if not sourced
if ! (return 0 2> /dev/null); then
    _initVariables "${@}"
    _initLogger "${@}"
    _initUtils
    _setTraps
    _traceVariables "${@}"
    _main "${scriptParams[@]}"
fi
